@startuml
!include C4_Component.puml

Component(auth, "Auth", "Autenticação")
Component(orders, "Orders", "Gestão de pedidos")
Component(users, "Users", "Gestão de usuários")

Rel(auth, users, "Valida")
Rel(orders, users, "Consulta")
@enduml 