@startuml
!pragma layout smetana
' version 1.2023.7
!include C4_Component.puml

Container_Boundary(api, "API") {
    Component(auth, "Auth", "Autenticação")
    Component(users, "Users", "Gestão de usuários")
    Component(orders, "Orders", "Pedidos")
}

Rel(auth, users, "Valida")
Rel(users, orders, "Gerencia")
@enduml 