@startuml "DDD e Arquitetura Hexagonal"

[Camada de Interfaces] as interfaces
[Camada de Aplicação] as app
[Camada de Domínio] as domain
[Camada de Infraestrutura] as infra

interfaces --> app
app --> domain
infra --> domain

@enduml 