@startuml
!pragma layout smetana
' version 1.2023.7
!include C4_Code.puml

Class(Order) {
    +id: string
    +status: string
    +create()
    +update()
}

Class(User) {
    +id: string
    +name: string
    +email: string
}

Order --> User
@enduml 